// Animation timing constants
export const ANIMATION_TIMING = {
  HEART_ANIMATION_DURATION: 1000, // ms
  HEART_ANIMATION_DELAY_STEP: 0.1, // seconds
  HEADER_FADE_DELAY: 0.2, // seconds
  CARD_FADE_DELAY: 0.3, // seconds
  BADGE_FADE_DELAY: 0.5, // seconds
  TEXT_FADE_DELAY: 0.6, // seconds
  BUTTON_FADE_DELAY: 0.8, // seconds
  HINT_FADE_DELAY: 1.2, // seconds
} as const;

// Animation values
export const ANIMATION_VALUES = {
  FLOATING_HEARTS_COUNT: 10,
  FLOATING_HEARTS_TARGET_Y: -100,
  HEADER_INITIAL_Y: -20,
  CARD_INITIAL_SCALE: 0.9,
  CARD_INITIAL_ROTATE_Y: -10,
  SPRING_STIFFNESS: 100,
  SPRING_DAMPING: 15,
  HEART_ANIMATION_DURATION_SECONDS: 2,
  DECORATIVE_EMOJI_FLOAT_DURATION: 3,
  DECORATIVE_EMOJI_FLOAT_DURATION_ALT: 4,
} as const;
