/**
 * Custom Service Worker - Background Sync for Mood Syncing
 *
 * This extends the Workbox-generated service worker to add
 * Background Sync API support for syncing pending moods.
 *
 * REAL Background Sync Implementation:
 * - Opens IndexedDB directly (no window context needed)
 * - Reads pending moods from IndexedDB
 * - Calls Supabase REST API via fetch (not JS client)
 * - Works even when app is completely closed
 *
 * Part of Hybrid Sync Solution:
 * - Immediate sync (App.tsx) - on mood creation
 * - Periodic sync (App.tsx) - while app is open
 * - Background Sync (here) - when app is closed or offline then online
 */

/// <reference lib="webworker" />

import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import type { MoodSyncPayload } from './services/moodSyncPayload';
import { moodSyncFingerprint, moodSyncPayload } from './services/moodSyncPayload';
import { MOOD_SYNC_LOCK, withSyncLock } from './services/syncLock';
import { getAuthToken, getPendingMoods, markMoodSynced } from './sw-db';

// Background Sync API types
interface SyncEvent extends ExtendableEvent {
  readonly tag: string;
  readonly lastChance: boolean;
}

// Service Worker type definitions
// PrecacheEntry defined in sw-types.d.ts
interface PrecacheEntry {
  url: string;
  revision?: string | null;
}

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<PrecacheEntry | string>;
};

// Auto-update: activate new SW immediately and claim all clients.
// Required by vite-plugin-pwa injectManifest + registerType: 'autoUpdate'.
// See: https://vite-pwa-org.netlify.app/guide/inject-manifest
self.skipWaiting();
clientsClaim();

// Supabase configuration from environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY as string;

// Precache JS, CSS, images, and fonts (generated by VitePWA)
// Note: index.html is NOT precached — NavigationRoute handles it with NetworkFirst
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Navigation requests: NetworkFirst to ensure fresh index.html
// Falls back to precached version only when offline
const navigationHandler = new NetworkFirst({
  cacheName: 'navigation-cache',
  networkTimeoutSeconds: 3,
});
registerRoute(new NavigationRoute(navigationHandler));

// Static assets (images, fonts) - Cache First for performance
registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new CacheFirst({
    cacheName: 'static-assets-v2',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Google Fonts - Cache First with long expiration
registerRoute(
  ({ url }) =>
    url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-v2',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

/**
 * Background Sync Event Handler
 *
 * Triggers when:
 * 1. Browser regains connectivity after being offline
 * 2. Sync is manually triggered via registration.sync.register()
 *
 * This ACTUALLY syncs pending moods from IndexedDB to Supabase,
 * even when the app is completely closed.
 */
self.addEventListener('sync', ((event: SyncEvent) => {
  if (event.tag === 'sync-pending-moods') {
    console.log('[ServiceWorker] Background Sync triggered:', event.tag);
    event.waitUntil(syncPendingMoods());
  }
}) as EventListener);

const MOODS_ENDPOINT = `${SUPABASE_URL}/rest/v1/moods`;

/**
 * Build the shared REST headers for a mood write
 */
function moodRequestHeaders(accessToken: string, prefer: string): HeadersInit {
  return {
    'Content-Type': 'application/json',
    apikey: SUPABASE_ANON_KEY,
    Authorization: `Bearer ${accessToken}`,
    Prefer: prefer,
  };
}

/**
 * Insert a mood, resolving to the existing row on conflict
 *
 * (user_id, created_at) is unique and created_at is the client-supplied log
 * time, so a record this device already wrote — by a retry, a second tab, or
 * the main thread — resolves to that row instead of adding another one.
 */
async function upsertMood(
  supabaseMood: MoodSyncPayload,
  accessToken: string
): Promise<Response> {
  return fetch(`${MOODS_ENDPOINT}?on_conflict=user_id,created_at`, {
    method: 'POST',
    headers: moodRequestHeaders(accessToken, 'resolution=merge-duplicates,return=representation'),
    body: JSON.stringify(supabaseMood),
  });
}

/**
 * Update an already-synced mood in place
 *
 * Mirrors moodSyncService.syncMood: user_id and created_at are deliberately
 * omitted from the body so the original log time survives the edit.
 */
async function patchMood(
  supabaseMood: MoodSyncPayload,
  accessToken: string,
  supabaseId: string
): Promise<Response> {
  return fetch(`${MOODS_ENDPOINT}?id=eq.${encodeURIComponent(supabaseId)}`, {
    method: 'PATCH',
    headers: moodRequestHeaders(accessToken, 'return=representation'),
    body: JSON.stringify({
      mood_type: supabaseMood.mood_type,
      mood_types: supabaseMood.mood_types,
      note: supabaseMood.note,
    }),
  });
}

/**
 * Sync pending moods, but only if no open tab is already doing it
 *
 * The app's own guard is `syncStatus.isSyncing` in the Zustand store, which
 * this worker cannot see. Without the lock, this batch and a tab's batch can
 * write the same record concurrently, and each then concludes its own write
 * was the current one — clearing the dirty flag over the other's edit.
 */
async function syncPendingMoods(): Promise<void> {
  const outcome = await withSyncLock(MOOD_SYNC_LOCK, runPendingMoodSync);

  if (!outcome.ran) {
    console.log('[ServiceWorker] A tab is already syncing moods - deferring this batch');
    // Throw so the `waitUntil` promise rejects. Background Sync only re-fires a
    // tag when its work rejects; resolving here would retire the registration
    // on a batch that did nothing, spending the one-shot retry guarantee the
    // offline path depends on.
    throw new Error('mood sync lock held by another context');
  }
}

/**
 * Sync pending moods from IndexedDB to Supabase
 *
 * This is the REAL background sync implementation:
 * 1. Opens IndexedDB directly (works without window)
 * 2. Gets the stored auth token
 * 3. Gets that token owner's pending moods
 * 4. Calls Supabase REST API with fetch
 * 5. Records the outcome against each mood
 */
async function runPendingMoodSync(): Promise<void> {
  try {
    // 1. Get auth token from IndexedDB
    //
    // Read before the moods, not after: the token names the account this pass
    // is allowed to act for, and every row below is stamped with its user id.
    // Reading the moods first meant the worker picked up whatever was pending
    // for any account that had ever signed in on this device and uploaded it
    // under whoever happened to be signed in now.
    const authToken = await getAuthToken();

    if (!authToken) {
      console.log('[ServiceWorker] No auth token available - will retry on next sync');
      // Don't throw - let the sync retry mechanism handle this
      return;
    }

    // Check if token is expired (with 5 minute buffer)
    const now = Math.floor(Date.now() / 1000);
    if (authToken.expiresAt && authToken.expiresAt < now + 300) {
      console.log('[ServiceWorker] Auth token expired - will sync when app refreshes token');
      // Don't throw - let the app refresh the token on next open
      return;
    }

    // 2. Get that user's pending moods from IndexedDB
    const pendingMoods = await getPendingMoods(authToken.userId);

    if (pendingMoods.length === 0) {
      console.log('[ServiceWorker] No pending moods to sync');
      return;
    }

    console.log(`[ServiceWorker] Found ${pendingMoods.length} pending moods to sync`);

    // 3. Sync each mood to Supabase via REST API
    let successCount = 0;
    let failCount = 0;
    let deferredCount = 0;

    for (const mood of pendingMoods) {
      if (!mood.id) {
        console.error('[ServiceWorker] Mood missing local ID, skipping');
        failCount++;
        continue;
      }

      try {
        const supabaseMood = moodSyncPayload(mood, authToken.userId);

        // Fingerprint BEFORE the fetch: an open tab can edit this record while
        // the request is in flight, and markMoodSynced must be able to tell.
        const sentFingerprint = moodSyncFingerprint(mood);

        // Call Supabase REST API directly. A record that already has a server
        // row is edited in place; everything else upserts, so this worker can
        // never duplicate a row the main thread already wrote.
        let response: Response;
        let rows: Array<{ id?: string }> = [];

        if (mood.supabaseId) {
          response = await patchMood(supabaseMood, authToken.accessToken, mood.supabaseId);
          if (response.ok) {
            rows = await response.json();
          }

          // Row deleted server-side: PostgREST reports that as a 404, or as a
          // 200 with an empty array. Either way fall back to the upsert so the
          // edit is not lost.
          if (response.status === 404 || (response.ok && rows.length === 0)) {
            response = await upsertMood(supabaseMood, authToken.accessToken);
            rows = response.ok ? await response.json() : [];
          }
        } else {
          response = await upsertMood(supabaseMood, authToken.accessToken);
          rows = response.ok ? await response.json() : [];
        }

        if (!response.ok) {
          const errorText = await response.text();
          console.error(
            `[ServiceWorker] Failed to sync mood ${mood.id}:`,
            response.status,
            errorText
          );
          failCount++;
          continue;
        }

        // Read the Supabase ID out of the representation returned above
        const [created] = rows;

        if (!created?.id) {
          console.error('[ServiceWorker] No ID in Supabase response for mood', mood.id);
          failCount++;
          continue;
        }

        // 4. Record the outcome in IndexedDB
        const outcome = await markMoodSynced(mood.id, created.id, sentFingerprint);

        if (outcome === 'deferred') {
          // Written, but a tab edited it mid-flight. Not a failure: the record
          // stays pending so the newer value reaches the server next pass.
          deferredCount++;
          console.log(`[ServiceWorker] Mood ${mood.id} edited during sync - left pending`);
        } else if (outcome === 'missing') {
          // Deleted locally while in flight. Nothing to report to the user as
          // synced — there is no local record left for the count to describe.
          console.log(`[ServiceWorker] Mood ${mood.id} was deleted during sync`);
        } else {
          successCount++;
          console.log(`[ServiceWorker] Synced mood ${mood.id} → ${created.id}`);
        }
      } catch (moodError) {
        console.error(`[ServiceWorker] Error syncing mood ${mood.id}:`, moodError);
        failCount++;
      }
    }

    console.log(
      `[ServiceWorker] Sync complete: ${successCount} succeeded, ${failCount} failed, ${deferredCount} deferred`
    );

    // 5. Notify open clients that sync completed
    const clients = await self.clients.matchAll({ type: 'window' });
    for (const client of clients) {
      client.postMessage({
        type: 'BACKGROUND_SYNC_COMPLETED',
        successCount,
        failCount,
      });
    }

    // Throw to trigger a Background Sync retry when nothing landed cleanly.
    // A deferred record was written but is still pending a newer value, and
    // unlike the main thread this worker has no second pass — so a deferral
    // must also re-fire, or the newer value is stranded until some unrelated
    // trigger fires.
    if (successCount === 0 && (failCount > 0 || deferredCount > 0)) {
      throw new Error(`No moods synced: ${failCount} failed, ${deferredCount} deferred`);
    }
  } catch (error) {
    console.error('[ServiceWorker] Background sync failed:', error);
    throw error; // Re-throw to trigger retry via Background Sync API
  }
}

// Log activation (skipWaiting + clientsClaim are handled at top level)
self.addEventListener('activate', (() => {
  console.log('[ServiceWorker] Activated - Background Sync ready');
}) as EventListener);
