/**
 * Custom Service Worker - Background Sync for Mood Syncing
 *
 * This extends the Workbox-generated service worker to add
 * Background Sync API support for syncing pending moods when
 * the app is closed or in the background.
 *
 * Part of Hybrid Sync Solution:
 * - Periodic sync (App.tsx) - while app is open
 * - Background Sync (here) - when app is closed
 * - Immediate sync (App.tsx) - on app mount
 */

/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

// Background Sync API types
interface SyncEvent extends ExtendableEvent {
  readonly tag: string;
  readonly lastChance: boolean;
}

// Service Worker type definitions
declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any[];
}

// Precache all static assets (generated by VitePWA)
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

/**
 * Background Sync Event Handler
 *
 * Triggers when:
 * 1. Browser regains connectivity after being offline
 * 2. Sync is manually triggered via registration.sync.register()
 *
 * This syncs pending moods from IndexedDB to Supabase
 */
self.addEventListener('sync', ((event: SyncEvent) => {
  if (event.tag === 'sync-pending-moods') {
    if (import.meta.env.DEV) {
      console.log('[ServiceWorker] Background Sync triggered:', event.tag);
    }

    // Wait for sync to complete before resolving
    event.waitUntil(syncPendingMoods());
  }
}) as EventListener);

/**
 * Sync pending moods from IndexedDB to Supabase
 *
 * This is called by the Background Sync API when the browser
 * has connectivity and the sync tag is registered.
 */
async function syncPendingMoods(): Promise<void> {
  try {
    // Send message to all clients to trigger sync
    const clients = await self.clients.matchAll({ type: 'window' });

    if (clients.length > 0) {
      // If app is open, notify it to sync
      for (const client of clients) {
        client.postMessage({
          type: 'BACKGROUND_SYNC_REQUEST',
          tag: 'sync-pending-moods',
        });
      }

      if (import.meta.env.DEV) {
        console.log('[ServiceWorker] Sent sync request to', clients.length, 'client(s)');
      }
    } else {
      // If no clients (app is closed), we can't access IndexedDB or Supabase directly
      // The sync will happen when the app is next opened
      if (import.meta.env.DEV) {
        console.log(
          '[ServiceWorker] No clients available - sync will happen on next app open'
        );
      }
    }
  } catch (error) {
    console.error('[ServiceWorker] Background sync failed:', error);
    throw error; // Re-throw to trigger retry
  }
}

/**
 * Message Handler
 *
 * Receives messages from the main app to control sync behavior
 */
self.addEventListener('message', ((event: ExtendableMessageEvent) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
}) as EventListener);

// Log when service worker is activated
self.addEventListener('activate', ((event: ExtendableEvent) => {
  if (import.meta.env.DEV) {
    console.log('[ServiceWorker] Activated - Background Sync ready');
  }
  event.waitUntil(self.clients.claim());
}) as EventListener);
